### ISSUE TITLE
Please switch from setup-ghdl-ci to setup-ghdl

### ISSUE THREAD

**Issue by Paebbels** [myhdl/myhdl#449]
> [!CAUTION]
> This GitHub Action (`setup-ghdl-ci`) has been **deprecated** in favor of the new [setup-ghdl](https://github.com/ghdl/setup-ghdl) Action.
> Please update your YAML files and transition to the new GitHub Action. See the linked repository for details on optional parameters.

**Quick example:**
```yml
jobs:
  GHDL-on-Ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: Run VHDL Simulation
        uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: mcode
```

**Why has it been changed?**  
* The Javascript GitHub Action is hard to maintain.  
  In addition, it has a high complexity with Node.js and other tools compare to a much simpler Composite Action using simple shell instructions in Bash/Powershell.
* This action doesn't support the `ubuntu-24.04` (= `ubuntu-latest`) runner image.
* This Action uses wrong tagging to select GHDL versions. See analysis: https://github.com/ghdl/ghdl/issues/2852
* Due to changes in GHDL's nightly releases and attached assets, the filenames are broken.

-----------------------
This repository has been listed by [Dependabot](https://github.com/ghdl/setup-ghdl-ci/network/dependents) as a dependent of `setup-ghdl-ci`.

**Comment by davekeeshan** [comment]
@Paebbels I have made the changes to the CI flow, however the `backend: llvm`, does not appear to be recognised.  myhdl only uses the `setup-ci` from the windows configuration.

https://github.com/myhdl/myhdl/actions/runs/12756629221/job/35555176047?pr=450

![image](https://github.com/user-attachments/assets/8d31f277-0ecc-47c3-932b-5ecf9d304bad)

The documentation suggests that this is the correct way:

https://github.com/ghdl/setup-ghdl#input-parameters

**Comment by Paebbels** [comment]
@davekeeshan is this your YAML code?
```
      - if: ${{ env.CI_TARGET == 'ghdl' }}
        uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: llvm
```

I assume you want to run GHDL with LLVM backend within MSYS2, right? MSYS2 is setup (green arrow).  
But `setup-ghdl` sets up GHDL for Windows native, not for MSYS2 (red arrow).

![image](https://github.com/user-attachments/assets/05a8d2cd-3ea1-483f-a604-fadd664b1cae)

In case of MSYS2, you also need to specify the `runtime` parameter, otherwise the action cannot decide if to run a powershell (native windows) a bash (git bash in native windows) or a bash inside of MSYS2 with MinGW64.

The documentation lists this example code:
```yaml
  GHDL-on-Windows-with-UCRT64:
    runs-on: windows-2022
    steps:
      - name: 🟦 Setup MSYS2 for UCRT64
        uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true

      - name: Run VHDL Simulation
        uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: mcode
          runtime: ucrt64
```

UCRT64 is similar to MinGW64. Actually, you should transition from MinGW64 to UCRT64, as this runtime is declining inside of MSYS2.

The `runtime` parameter is documented as follows:
> If runner OS is Windows, a MSYS2 runtime can be selected (mingw64, ucrt64). If not set, Windows native is used (not MSYS2 environment).

Any suggestions on changing the documentation?

The LLVM backend doesn't exist (yet?) for native Windows.

------------------
Btw, you can simplify this code:
```yaml
if: ${{ env.CI_TARGET == 'ghdl' }}
```
to
```yaml
if: matrix.target == 'ghdl'
```
* no need for ${{ ... }}}
* no need for an intermediate global environment variable  
  Please also be aware of several serious issues in GitHub Actions to the order of environment variable evaluations. Basically, you can consider this feature totally broken except for very basic usage models. A rule of thumb tries to avoid environment variables in GitHub's YAML code. (This bug/feature was reported when GitHub Action was still in testing phase several years ago).

**Comment by davekeeshan** [comment]
@Paebbels Thanks for that, I needed to make sure path-type was also included, without it actions could not find python.

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          path-type: inherit
          update: true

Thanks for the improvement notes, I think some might have been there from a legacy perspective, but it is good to have a fresh set of eyes every few years.

I have also moved the whole flow, including the linux part under `ghdl/setup-ghdl` the quality of the ghdl actions nightly build seems to be up to par now. (I wish there was one for icarus too)

**Comment by Paebbels** [comment]
@davekeeshan I think your MSYS2 is not setup correctly.

> I needed to make sure path-type was also included, without it actions could not find python.

This means you're using the Python from Windows, not the Python within MSYS2/UCRT64. While this is technically possible (as you achieved it), it's not recommended nor does your test environment behave like other user's environments look like. For a "correct" setup, install Python within MSYS2.

```yaml
  - uses: msys2/setup-msys2@v2
    with:
      msystem: ucrt64
      update: true
      install: git                             # MSYS2 packages like git, make, ...
      pacboy: python-pip:p python-wheel:p      # runtime specific packages like Python
```

`pacboy` is a helper program like `pacman`. I uses `<name>:p` for packages and automatically resolves the package name to a mingw64 or ucrt64 package name.
In case you need normal programs, I also added how to install `git`. If not needed, please remove that with-parameter.

---------------------
> I have also moved the whole flow, including the linux part under ghdl/setup-ghdl the quality of the ghdl actions nightly build seems to be up to par now. 

All builds on GHDL's main branch is very stable. We move the nightly tag from time to time. So it should be as stable as the main builds. In case we get problems reported, Tristan usually pushes a fix within days to the main branch or we could revert the nightly tag.
